### ISSUE TITLE
MVPレヴュー

### ISSUE THREAD

**Issue by iijima-naoya-45b** [iijima-naoya-45b/Qmeals#105]
標記になります。よろしくお願いします。

### 概要
「時短」「手軽に」をモットーに、料理の楽しさを知ってもらう為のアプリです。

アプリの詳細 https://github.com/iijima-naoya-45b/Qmeals
アプリのURL https://qmeals-app.onrender.com

### 実装未定の機能
- [ ] レシピの編集
- [ ] 料理の知恵袋の編集
- [ ] 通知機能
- [ ] レーティング機能

### 実装予定の機能
- [ ] 管理画面

### 必要なページ
- [ ] LP(トップページ)
- [ ] 問い合わせ画面
- [ ] プライバシーポリシー画面
- [ ] 利用規約画面
- [ ] ユーザー登録画面
- [ ] ログイン画面
- [ ] レシピの投稿一覧
- [ ] レシピの詳細画面
- [ ] レシピの新規作成画面
- [ ] 料理の知恵袋一覧
- [ ] 料理の知恵袋一覧
- [ ] 料理の知恵袋新規作成画面
- [ ] パスワードリセット画面
- [ ] ユーザー情報編集画面
- [ ] ユーザー情報画面
- [ ] 買い物リスト一覧画面
- [ ] 買い物リスト新規画面
- [ ] お気に入り画面
- [ ] EdamamAPIの検索画面

**Comment by Tsuchiya2** [comment]
LGTMです
